# Regenerates data/bot-extra-blocklist.txt from public datasets (world cities CSV + country names).
# City name tokens: length >= 8 (reduces blocking common English words like "spring", "hope").
# Country name tokens: length >= 5.
# Run from repo root: powershell -ExecutionPolicy Bypass -File scripts/generate-bot-extra-blocklist.ps1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot\..
$wc = Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/datasets/world-cities/master/data/world-cities.csv' -UseBasicParsing -TimeoutSec 120
$lines = $wc.Content -split "`r?`n"
$stop = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($s in @('new','old','big','red','greater','lesser','upper','lower','north','south','east','west','los','las','san','santa')) {
  [void]$stop.Add($s)
}
$words = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
foreach ($line in $lines | Select-Object -Skip 1) {
  if (-not $line) { continue }
  $name = ($line -split ',')[0]
  if (-not $name) { continue }
  foreach ($part in ($name.ToLowerInvariant() -split '[^a-z]+')) {
    if ($part.Length -lt 8) { continue }
    if ($stop.Contains($part)) { continue }
    if ($part -match '^[a-z]+$') { [void]$words.Add($part) }
  }
}
$countries = (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/umpirsky/country-list/master/data/en/country.txt' -UseBasicParsing).Content -split "`r?`n"
foreach ($line in $countries) {
  foreach ($part in ($line.ToLowerInvariant() -split '[^a-z]+')) {
    if ($part.Length -ge 5 -and $part -match '^[a-z]+$') { [void]$words.Add($part) }
  }
}
$sorted = $words | Sort-Object
$header = @(
  '# Bot extra blocklist: placename tokens (8+ chars) + country tokens (5+ chars).',
  '# Auto-generated by scripts/generate-bot-extra-blocklist.ps1',
  '# Does not affect player dictionary validation.'
)
$header + $sorted | Set-Content -Path 'data\bot-extra-blocklist.txt' -Encoding utf8
Write-Host ('Wrote data/bot-extra-blocklist.txt — ' + $sorted.Count + ' words')
